name: backport
on:
  # pull_request_target:
  #   types: [closed]
  pull_request:
    types: 
      - closed
    branches: 
       - main

jobs:
  back-porting:
    name: backport to release branches
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'backport-requested')
    runs-on: ubuntu-20.04    
    strategy:
      fail-fast: false
      matrix:
        branch: 
          -  release-1.16
          -  release-1.17
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      - 
        id: findPr
        uses: jwalton/gh-find-current-pr@v1.3.2
        with: 
          state: closed
      - 
        name: Check labels
        if: success() && steps.findPr.outputs.number
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ steps.findPr.outputs.pr }}
        run: |
          echo "pull request to backport is ${PR}"
          label=$(gh pr view ${PR} --json labels -q ".labels.[].name" 2>/dev/null | grep ${{ matrix.branch }} || :) 
          echo "LABEL=${label}" >> $GITHUB_ENV
          echo "label find out is ${{ env.LABEL }} ${label}"
      - 
        name: cherry pick
        if: success() && ${{ env.LABEL }} == ${{ matrix.branch }}
        env: 
          PR: ${{ steps.findPr.outputs.pr }}
        run: |
           echo "cherry-pick ${PR} to branch ${{ matrix.branch }}"
           commit=$(gh pr view ${PR} --json mergeCommit -q ".mergeCommit.oid" 2>/dev/null || :) 
           if [[ "$commit" != "" ]]; then
              git checkout -b cherry-pick-${{ matrix.branch }}-${PR}
              git cherry-pick $commit
              git push 
           fi
      - 
        name: create pull request
        uses: gr2m/create-or-update-pull-request-action@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          PR: ${{ steps.findPr.outputs.pr }}
        with:
          title: "backport pr ${PR} to branch ${{ matrix.branch }}"
          branch: cherry-pick-${{ matrix.branch }}-${PR}

           











      # - name: Cherry pick into ${{ matrix.release-branch }}
      #   # if: contains(github.event.pull_request.labels.*.name, ${{ matrix.release-branch }})
      #   uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
      #   with:
      #     branch: release-1.17
      #     labels: |
      #       backport

