name: backport
on:
  # pull_request_target:
  #   types: [closed]
  pull_request:
    types: 
      - closed
    branches: 
       - main

jobs:
  back-porting:
    name: backport to release branches
    if: github.event.pull_request.merged == true 
    runs-on: ubuntu-20.04
    # strategy:
    #   matrix:
    #     release-branch: 
    #       - "release-1.16"
    #       - "release-1.17"
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: backport to release branches
        uses: tibdex/backport@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # - name: Cherry pick into ${{ matrix.release-branch }}
      #   # if: contains(github.event.pull_request.labels.*.name, ${{ matrix.release-branch }})
      #   uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
      #   with:
      #     branch: release-1.17
      #     labels: |
      #       backport

