name: backport
on:
  # pull_request_target:
  #   types: [closed]
  pull_request:
    types: 
      - closed
    branches: 
       - main

jobs:
  back-porting:
    name: backport to release branches
    if: github.event.pull_request.merged == true && contains(github.event.pull_request.labels.*.name, 'backport-requested')
    runs-on: ubuntu-20.04    
    strategy:
      fail-fast: false
      matrix:
        branch: 
          -  release-1.16
          -  release-1.17
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      - 
        name: Check preconditions
        id: get_pr_number_and_labels
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo ${{ matrix.branch }}
          pull_number=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "PR_NUMBER=${pr_number}" >> $GITHUB_ENV
          label=$(gh pr view --json labels -q ".labels.[].name" 2>/dev/null || : | grep ${{ matrix.branch }})
          echo "LABEL=${label}" >> $GITHUB_ENV
          echo ${{ env.PR_NUMBER}}
          echo ${{ env.LABEL}}










      # - name: Cherry pick into ${{ matrix.release-branch }}
      #   # if: contains(github.event.pull_request.labels.*.name, ${{ matrix.release-branch }})
      #   uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
      #   with:
      #     branch: release-1.17
      #     labels: |
      #       backport

