name: backport
on:
  # pull_request_target:
  #   types: [closed]
  pull_request:
    types: [closed]

jobs:
  if_merged:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: find pr
        uses: juliangruber/find-pull-request-action@v1
        id: find-pull-request
        with:
          state: closed
          base: 'main'
      - name: echo
        run: |
          echo "${{ steps.find-pull-request.outputs.number }}" 
          echo "${{ steps.find-pull-request.outputs.base-sha }}" 
      - name: Cherry pick into release-v2.0
        uses: carloscastrojumo/github-cherry-pick-action@v1.0.1
        with:
          branch: release-1.15
          labels: |
            backports 
          reviewers: |
            aReviewerUser

  
