name: slash-command-dispatcher
on:
  issue_comment:
    types: [created]

jobs:
  test-dispatcher:
    runs-on: ubuntu-20.04
    steps:
      - name: dispatcher message
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{secrets.TAO_PTO}}
          issue-type: pull-request
          permission: write
          commands: test
          static-args: |
            level=1
            pr_number=1cfde2

  auto-label:
    if: ${{ github.event.issue.pull_request }}
    runs-on: ubuntu-20.04
    steps:
      - name: echo
        run: | 
          echo ${{ github.event.comment.body }}
          echo ${{ github.event.issue.pull_request }}
          echo ${{ github.event.issue.pull_request.labels }}
          echo ${{ contains(github.event.issue.pull_request.labels.*.name,'ok-to-merge') }}
          echo ${{ contains(github.event.issue.pull_request.labels.*.name,'test') }}
          echo ${{ #github.event.issue.pull_request.labels.*.name[*] }}
      - name: autoLabel
        uses: actions-ecosystem/action-add-labels@v1.1.0
        if: ${{ startsWith(github.event.comment.body, '/ok-to-merge') }}
        with:
          github_token: ${{ secrets.TAO_PTO }}
          labels: ok-to-merge 