name: slash-command-receiver

on:
  repository_dispatch:
    types:
      - test-command
jobs:
  test-receiver:
    runs-on: ubuntu-20.04
    steps:
      - name: get branch name
        id: chaos
        run: |
          if [[ "${{ github.event.client_payload.pull_request.head.ref }}" != "" ]]
          then
            ref=${{ github.event.client_payload.pull_request.head.ref }}
            echo ::set-output name=ref::$ref
          fi
      - name: Invoke workflow-dispatch
        id: trigger-workflow
        uses: aurelien-baudet/workflow-dispatch@v2
        with:
          workflow: continuous-delivery
          token: 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
          ref: ${{ steps.chaos.outputs.ref }}
          display-workflow-run-url: true
          wait-for-completion: false
          inputs: '{"pr_number":${{ github.event.client_payload.github.payload.issue.number }}}'
      