name: continuous-delivery

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      pr_number:
          description: pull request number referenced
          required: false
      test:
          description: just for test
          required: false

    
jobs:
  comments-and-label:
    name: comments
    if: |
      always() &&
      (
        github.event_name == 'pull_request' ||
        github.event_name == 'workflow_dispatch'
      )
    runs-on: ubuntu-20.04
    steps:
      - name: check test level
        id: checkLevel
        if: always()
        run: |
          echo ${{github.event.inputs.pr_number}}
          echo ${{github.event.inputs.test}}
          echo ${{github.event.inputs}}
          if [[ ${{ github.event_name }} == 'pull_request' ]];
          then
            echo "::set-output name=prNumber::${{github.event.number}}"
          elif [[ ${{ github.event_name }} == 'workflow_dispatch' ]];
          then
            echo "::set-output name=prNumber::${{github.event.inputs.pr_number}}"
          fi
      - name: checkout
        uses: actions/checkout@v2
      - name: add label
        id: label
        if: always() &&
              steps.checkLevel.outputs.prNumber != '' 
        uses: actions-ecosystem/action-add-labels@v1
        with:
          number: ${{ steps.checkLevel.outputs.prNumber }}
          labels: pass,success,good